Capstone javascript project: Meals
NasKhalil/capstone-project pull request #37
Opened 2021-12-24 21:59 UTC by NasKhalil

## This branch includes the following features implemented:

- Use JavaScript to make websites dynamic and build basic single page apps.
- Use ES6 syntax.
- Use ES6 modules.
- Use callbacks and promises.
- Use webpack.
- Apply JavaScript best practices and language style guides in code.
- Use AAA pattern for unit tests.
- Write units tests for a JavaScript app.
- Follow Gitflow.
- Solve simple git conflicts.
- Send and receive data from an API.
- Use API documentation.
- Understand and use JSON.
- Make JavaScript code synchronous.
- Perform a code review for a team member.

2021-12-24 23:11 UTC, oloomoses requested changes
Hi team, 

You have really done a great job, especially on the video presentation.

There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

_Slack: Oloo Moses_
------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-24 23:11 UTC, oloomoses commented on README.md
> +[live-version](https://naskhalil.github.io/capstone-project/)
- [x] This link to the live demo loads the readme file instead of redirecting to the live demo. Kindly fix it.

2021-12-24 23:11 UTC, oloomoses commented on src/functions/displayList.js
> +    } else alert('Empty fields are not allowed');
- [ ] Kindly Do not use `alert()` It’s ugly, impossible to style, it stops code execution and displays differently on different browsers. Use custom modal instead.

2021-12-24 23:58 UTC, NasKhalil commented
Thanks @oloomoses for the feedback 👍

2021-12-25 00:06 UTC, oloomoses approved these changes
Hi team, 

Great job on making the suggested changes.
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

_Slack: Oloo Moses_
------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-25 01:45 UTC, merged